### ISSUE TITLE
Interested in collaboration?

### ISSUE THREAD

**Issue by aMOPel** [monaqa/old-tree-sitter-nim#1]
Hey there. I've put quite some time into a tree-sitter parser for Nim as well.

https://github.com/aMOPel/tree-sitter-nim

Would you be interested in collaborating?

**Comment by monaqa** [comment]
Excellent!! I am very interested.
Obviously, your repository is closer to complete version than mine.
I would love to contribute.

**Comment by aMOPel** [comment]
Damn, you made dial.nvim. Great plugin, using it with delight :)

I would be open to introducing you to my codebase in a call if you want. Or you wanna work into it yourself?

**Comment by aMOPel** [comment]
I have created a bunch of issues on the repo now. If you want to contribute you can state so in the respective issue and make a PR. Or if you want I can also make you a collaborator.

**Comment by monaqa** [comment]
Thank you so much!
I am going to check the code and the Issue first.

**Comment by aMOPel** [comment]
Thank you too :)

I've added a section to the readme with stuff from my vimrc to ease development, especially the writing of tests. Maybe it's useful to you.

The offer for a call still stands if you have any questions.
